-- Create 'subjects' table
CREATE TABLE IF NOT EXISTS public.subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  code TEXT UNIQUE,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;

-- Allow all access for now
CREATE POLICY "allow_all_subjects" ON public.subjects FOR ALL USING (true) WITH CHECK (true);

-- Insert some default subjects
INSERT INTO public.subjects (name, code, description)
VALUES 
('Mathematics', 'MATH-01', 'Core mathematics subject'),
('Science', 'SCI-01', 'General science subject'),
('English', 'ENG-01', 'English language and literature'),
('History', 'HIST-01', 'World and local history'),
('ICT', 'ICT-01', 'Information and Communication Technology')
ON CONFLICT (name) DO NOTHING;
