-- Create 'messages' table to store history
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID DEFAULT auth.uid(),
  recipient_type TEXT NOT NULL, -- 'Student' or 'Class'
  recipient_id BIGINT NOT NULL, -- ID of the student or class
  recipient_name TEXT,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'Sent',
  sent_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Allow all access for now
CREATE POLICY "allow_all_messages" ON public.messages FOR ALL USING (true) WITH CHECK (true);
