-- Create 'classes' table
CREATE TABLE IF NOT EXISTS public.classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name TEXT,
  subject TEXT,
  tutor TEXT,
  grade TEXT,
  day TEXT,
  start_time TIME,
  end_time TIME,
  fee NUMERIC(10, 2),
  status TEXT DEFAULT 'Active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

-- Allow all access
CREATE POLICY "allow_all_classes" ON public.classes FOR ALL USING (true) WITH CHECK (true);
