-- Create 'payments' table
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL,
  month TEXT NOT NULL, -- Format: "January 2024"
  payment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  payment_method TEXT DEFAULT 'Cash',
  receipt_no TEXT UNIQUE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Allow all access
CREATE POLICY "allow_all_payments" ON public.payments FOR ALL USING (true) WITH CHECK (true);
