-- Create 'roles' table
CREATE TABLE IF NOT EXISTS public.roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  permissions TEXT[], -- Array of strings for permissions
  color TEXT DEFAULT 'grey',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

-- Allow all access for now
CREATE POLICY "allow_all_roles" ON public.roles FOR ALL USING (true) WITH CHECK (true);

-- Insert default roles
INSERT INTO public.roles (name, description, permissions, color)
VALUES 
('Super Admin', 'Full Access to all system features', ARRAY['users', 'finance', 'settings', 'reports', 'classes'], 'red'),
('Clerk', 'Limited access to student registration and attendance', ARRAY['students', 'attendance'], 'teal')
ON CONFLICT (name) DO NOTHING;
