-- Run this entire script in your Supabase SQL Editor

-- 1. Create the 'students' table
CREATE TABLE IF NOT EXISTS public.students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id TEXT,
  name TEXT,
  grade TEXT,
  contact TEXT,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the 'tutors' table
CREATE TABLE IF NOT EXISTS public.tutors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  subject TEXT,
  email TEXT,
  phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable RLS (Row Level Security)
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tutors ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies to allow ALL access (Read, Write, Update, Delete)
-- Note: In a real production app, you might restrict this to authenticated users only.
-- For now, we allow access to anyone with the API key (Anon key) to ensure it works immediately.

CREATE POLICY "Enable all access for students" ON public.students
FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Enable all access for tutors" ON public.tutors
FOR ALL USING (true) WITH CHECK (true);
